name: voice_assistent
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  flutter_tts: ^3.6.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.2
  speech_to_text: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  riverpod_generator: ^2.1.4

flutter:
  uses-material-design: true
